# Generated by Django 4.0.4 on 2022-07-14 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loanInformation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('applicant_photo', 'applicant_photo'), ('address_proof', 'address_proof'), ('dob_proof', 'dob_proof')], max_length=100)),
                ('file_path', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_application_id', to='loanInformation.loanapplication')),
            ],
        ),
    ]
