# Generated by Django 4.0.4 on 2022-07-14 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('new', 'new'), ('verification_pending', 'verification_pending'), ('approved', 'approved'), ('rejected', 'rejected'), ('disturbed', 'disturbed')], max_length=100)),
                ('verification_status', models.CharField(choices=[('new', 'new'), ('assigned', 'assigned'), ('verified', 'verified'), ('failed', 'failed'), ('approved', 'approved'), ('rejected', 'rejected')], max_length=100)),
                ('loan_amount', models.CharField(max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_id', to='customer.customer')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='employee.employee')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to='employee.employee')),
                ('verifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifier', to='employee.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoanApplicationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('customer_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('new', 'new'), ('verification_pending', 'verification_pending'), ('approved', 'approved'), ('rejected', 'rejected'), ('disturbed', 'disturbed')], max_length=100)),
                ('verification_status', models.CharField(choices=[('new', 'new'), ('assigned', 'assigned'), ('verified', 'verified'), ('approved', 'approved'), ('rejected', 'rejected')], max_length=100)),
                ('manager_id', models.CharField(max_length=250)),
                ('verifier_id', models.CharField(max_length=250)),
                ('reviewer', models.CharField(max_length=250)),
                ('loan_amount', models.CharField(max_length=100)),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_loan_application_id', to='loanInformation.loanapplication')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
